version: '2'
services:
  configuremgmtsampleapplication-app:
    image: configuremgmtsampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://configuremgmtsampleapplication-postgresql:5432/ConfigureMgmtSampleApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  configuremgmtsampleapplication-postgresql:
    extends:
      file: postgresql.yml
      service: configuremgmtsampleapplication-postgresql
